# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

carmakes = CarMake.create([{ name: 'Acura' }, 
       { name: 'Alfa Romeo'},
{ name: 'Aston Martin'},
{ name: 'Audi'},
{ name: 'Bentley'},
{ name: 'BMW'},
{ name: 'Bugatti'},
{ name: 'Buick'},
{ name: 'Cadillac'},
{ name: 'Caterham'},
{ name: 'Chevrolet'},
{ name: 'Chrysler'},
{ name: 'Dodge'},
{ name: 'Ferrari'},
{ name: 'Fiat'},
{ name: 'Ford'},
{ name: 'GMC'},
{ name: 'Honda'},
{ name: 'Hyundai'},
{ name: 'Infiniti'},
{ name: 'Jaguar'},
{ name: 'Jeep'},
{ name: 'Kia'},
{ name: 'Lamborghini'},
{ name: 'Land Rover'},
{ name: 'Lexus'},
{ name: 'Lincoln'},
{ name: 'Lotus'},
{ name: 'Maserati'},
{ name: 'Mazda'},
{ name: 'Mercedes Benz'},
{ name: 'Mini'},
{ name: 'Mitsubishi'},
{ name: 'Nissan'},
{ name: 'Porsche'},
{ name: 'Ram Trucks'},
{ name: 'Rolls Royce'},
{ name: 'Smart'},
{ name: 'Subaru'},
{ name: 'Toyota'},
{ name: 'Tesla'},
{ name: 'Volkswagen'},
{ name: 'Volvo'}])